spring.application.name=ecombackend

spring.datasource.url=jdbc:postgresql://localhost:5432/mapsdb
spring.datasource.username=siddharth
spring.datasource.password=momdad
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true