# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mapsdb?schema=public
spring.datasource.username=siddharth
spring.datasource.password=momdad
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT - two separate secrets matching your NestJS JWT_SECRET / JWT_REFRESH_SECRET env vars
jwt.secret=044de8b89cd6b017d24f93abebcfab467717b8ce8b532d79c0aca117239e8ab4
jwt.refresh-secret=a477585356b74ad284c0581e2d1b6ecf380dc3d18bfed383cd3a817a5131b075
jwt.access-token.expiration=900000
# 15 minutes in ms
jwt.refresh-token.expiration=604800000
# 7 days in ms

# BCrypt - matches SALT_ROUNDS = 12 in your NestJS AuthService
bcrypt.salt-rounds=12

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce=DEBUG
